#!/bin/bash
# The grub-crypt script should exist in a sub-directory ./sbin relative to this build wrapper.
fpm -s dir -t rpm -a all -n grub-crypt --license 'GPLv3+' --description "The 'grub-crypt' Python script from Grub 0.9x. This is useful in creating password hashes for Kickstart or use in /etc/shadow." --iteration '1.el7' ./sbin